# Generated by Django 3.0.5 on 2020-04-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('phno', models.CharField(max_length=100)),
                ('st', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('work', models.CharField(max_length=100)),
                ('edu', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=100)),
                ('workexp', models.CharField(max_length=100)),
            ],
        ),
    ]
